import type { Permission, Role } from "./types"

export const ALL_PERMISSIONS: Permission[] = [
  "students:view",
  "students:create",
  "students:edit",
  "students:delete",
  "teachers:view",
  "teachers:create",
  "teachers:edit",
  "teachers:delete",
  "attendance:view",
  "attendance:mark",
  "academics:view",
  "academics:manage",
  "exams:view",
  "exams:manage",
  "results:publish",
  "fees:view",
  "fees:collect",
  "fees:manage",
  "reports:view",
  "reports:export",
  "settings:manage",
  "users:manage",
  "users:manage-roles",
  "hrms:view",
  "hrms:manage",
  "hrms:approve-leave",
  "transport:view",
  "transport:manage",
  "library:view",
  "library:manage",
  "admissions:view",
  "admissions:manage",
  "events:view",
  "events:manage",
  "announcements:view",
  "announcements:manage",
  "analytics:view",
  "audit:view",
  "calendar:manage",
]

const admin: Permission[] = [
  "students:view",
  "students:create",
  "students:edit",
  "students:delete",
  "teachers:view",
  "teachers:create",
  "teachers:edit",
  "teachers:delete",
  "attendance:view",
  "attendance:mark",
  "academics:view",
  "academics:manage",
  "exams:view",
  "exams:manage",
  "results:publish",
  "fees:view",
  "fees:manage",
  "reports:view",
  "reports:export",
  "settings:manage",
  "hrms:view",
  "hrms:manage",
  "hrms:approve-leave",
  "transport:view",
  "library:view",
  "admissions:view",
  "admissions:manage",
  "events:view",
  "events:manage",
  "announcements:view",
  "announcements:manage",
  "analytics:view",
  "audit:view",
  "calendar:manage",
]

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  // super_admin short-circuits to "all" in hasPermission() below
  super_admin: ALL_PERMISSIONS,
  principal: admin,
  vice_principal: admin.filter(
    (p) => p !== "hrms:manage" && p !== "settings:manage"
  ),
  teacher: [
    "students:view",
    "attendance:view",
    "attendance:mark",
    "academics:view",
    "academics:manage",
    "exams:view",
    "exams:manage",
    "events:view",
    "announcements:view",
    "announcements:manage",
    "hrms:view",
    "calendar:manage",
  ],
  accountant: [
    "students:view",
    "fees:view",
    "fees:collect",
    "fees:manage",
    "reports:view",
    "reports:export",
    "hrms:view",
    "hrms:manage",
    "analytics:view",
  ],
  receptionist: [
    "students:view",
    "students:create",
    "students:edit",
    "attendance:view",
    "fees:view",
    "fees:collect",
    "admissions:view",
    "admissions:manage",
    "events:view",
    "events:manage",
    "announcements:view",
    "reports:view",
  ],
  librarian: ["library:view", "library:manage", "students:view", "teachers:view"],
  transport_manager: [
    "transport:view",
    "transport:manage",
    "students:view",
    "reports:view",
  ],
  hostel_manager: ["students:view", "attendance:view", "transport:view"],
  parent: [
    "students:view",
    "attendance:view",
    "fees:view",
    "fees:collect",
    "exams:view",
    "academics:view",
    "transport:view",
    "library:view",
    "events:view",
    "announcements:view",
  ],
  student: [
    "attendance:view",
    "exams:view",
    "academics:view",
    "library:view",
    "events:view",
    "announcements:view",
  ],
}

export function hasPermission(role: Role, permission: Permission): boolean {
  if (role === "super_admin") return true
  return ROLE_PERMISSIONS[role].includes(permission)
}

export const DESTRUCTIVE_ACTION_ROLES = {
  deleteStudent: ["super_admin", "principal"] as Role[],
  deleteTeacher: ["super_admin", "principal"] as Role[],
  deleteUser: ["super_admin"] as Role[],
  editPermissionMatrix: ["super_admin"] as Role[],
  suspendUser: ["super_admin", "principal"] as Role[],
  approvePayroll: ["super_admin", "principal"] as Role[],
  approveLeave: ["super_admin", "principal", "vice_principal"] as Role[],
  publishResults: ["super_admin", "principal", "vice_principal"] as Role[],
  deleteFeeRecord: ["super_admin", "accountant"] as Role[],
  deleteAnnouncement: ["super_admin", "principal"] as Role[],
  deleteBook: ["super_admin", "librarian"] as Role[],
  deleteVehicle: ["super_admin", "transport_manager"] as Role[],
  approveAdmission: ["super_admin", "principal"] as Role[],
}
